server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nhutpm90/1invest-config-repo.git
          username: nhutpm90
          password: Nhutpham@092103
          force-pull: true
          skipSslValidation: true